embeddings {
  tensor_name: "Network:01302"
  metadata_path: "01302/Network/metadata.tsv"
  tensor_path: "01302/Network/tensors.tsv"
}
embeddings {
  tensor_name: "Island:01302"
  metadata_path: "01302/Island/metadata.tsv"
  tensor_path: "01302/Island/tensors.tsv"
}
embeddings {
  tensor_name: "Participant:01302"
  metadata_path: "01302/Participant/metadata.tsv"
  tensor_path: "01302/Participant/tensors.tsv"
}
embeddings {
  tensor_name: "FlowDirection:01302"
  metadata_path: "01302/FlowDirection/metadata.tsv"
  tensor_path: "01302/FlowDirection/tensors.tsv"
}
