name: hack
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch==2.0.1
  - pytorch-lightning==2.0.6
  - tensorboardx
  - pytest
  - pandas
  - pyarrow
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: 1
